version: '2'

services:
  openssh-server: 
    build: .
    image: hackinglab/alpine-openssh-server:3.2
    environment:
    - AUTHOR=e1
    - HL_USER_USERNAME=hacker
    - HL_USER_PASSWORD=compass
    ports:
      - "2222:22"

